'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LynderWorld.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Public ReadOnly Property adv1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property adv10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property adv11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property adv12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property adv13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property adv14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property adv15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property adv2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property adv3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property adv4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property adv5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property adv6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property adv7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property adv8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property adv9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adv9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property EvilHard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EvilHard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property faceA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("faceA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property favicon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property ferreiro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ferreiro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property hp_potion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hp_potion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property magoCura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magoCura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property mana_potion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mana_potion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property mapa2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapa2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property medieval() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medieval", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property medieval2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medieval2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property medieval3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medieval3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property medieval4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medieval4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property medieval58() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medieval58", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property medieval6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medieval6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property medieval61() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medieval61", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property npc1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("npc1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property npc2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("npc2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property npc3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("npc3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property npc4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("npc4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property npc5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("npc5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property per1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("per1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property per2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("per2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property per3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("per3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property per4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("per4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property per5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("per5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property per6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("per6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property principal() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("principal", resourceCulture)
            End Get
        End Property
        
        Public ReadOnly Property supreme_potion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supreme_potion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property vs1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vs1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
